### ISSUE TITLE
-273 C with lepton 3

### ISSUE THREAD

**Issue by technoturk** [danjulio/lepton#18]
im useing a lepton 3 on the t cam mini rev2, i can get a good thermal image but the S & M1, 4 temperatures gives me a fixed -273 Celcius valeu, 
Is this because the software is made for the lepton 3,5 ? 
If so will be there a lepton 3 FW choice  or does this need a hardware mode to ?

**Comment by danjulio** [comment]
Hello technoturk,

I think you must be using a pre version 2.0 Desktop app that doesn't have support for Lepton 3 (that was added to the Desktop app in version 2.0).  In the 2.0 application I suppress all temperature display and disable the spot and markers.

This is because the Lepton 3.0 does not support radiometric data output (which is why I originally didn't support it).  So it is not possible to easily extract temperature data from its output. 

I added support for the 3.0 so people who had them laying around could at least get good images out of tCam-Mini and the software wouldn't malfunction (as you are seeing).

I realize this isn't probably the answer you were hoping for but I hope it explains what you are seeing.
